### ISSUE TITLE
ItemCollection as linked STAC Object

### ISSUE THREAD

**Issue by matthewhanson** [stac-extensions/item-collection#3]
An ItemCollection should be a proper STAC object, which means it's has root, parent, and possibly self link for. The self link would work the same as a `next` or `prev` link, except that `merge` should be False so that the payload is actually provided (if using POST). 

This isn't just for consistency with other STAC objects, it's also practical when saving results since it contains a record of the request and API source.

**Comment by philvarner** [comment]
I'm not certain that the semantics of self actually apply here, because the search results are not a "proper" RESTful resource.  I think that info would be better to capture in the Context object as "source query" or something.

**Comment by matthewhanson** [comment]
In thinking about this more and working on pystac-api-client, I've concluded that there is little to be gained by making a FeatureCollection an actual STAC object. They won't appear in static catalogs, are typically dynamically generated, and don't think it makes sense to add stac_version, stac_extensions, etc. at the top-level of a FeatureCollection. It is just a collection of Items, and each of those can be validated and even could be different versions.

So I don't think it's high priority to even have a Schema here, it will just be:
- type: FeatureCollection
- features: Items
- links: for pagination

I think what I've really been after here is just to be able to work easily with FeatureCollections in PySTAC. This can just be added in as a set of utility functions and doesn't require a formal extension.

**Comment by m-mohr** [comment]
So we'll drop this extension repo and just leave it in the API fragments? @matthewhanson

**Comment by matthewhanson** [comment]
@m-mohr Yes I think that's fine.  We'll add in utility class for working with an ItemCollection in PySTAC, but treating ItemCollection as an actual STAC object appears fraught with difficulty, not the least of which is validation.
